"""empty message

Revision ID: 306b702c7972
Revises: b6a133a2c49a
Create Date: 2020-08-24 19:33:59.076070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306b702c7972'
down_revision = 'b6a133a2c49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
