"""empty message

Revision ID: 6b0c3a2e571a
Revises: 306b702c7972
Create Date: 2020-08-25 20:08:23.587262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0c3a2e571a'
down_revision = '306b702c7972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('now', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'now')
    # ### end Alembic commands ###
