"""empty message

Revision ID: 7337efe8e369
Revises: c0d34225550c
Create Date: 2020-08-28 19:31:38.474542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7337efe8e369'
down_revision = 'c0d34225550c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fid', 'uid')
    )
    op.add_column('user', sa.Column('fans', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('follows', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'follows')
    op.drop_column('user', 'fans')
    op.drop_table('follow')
    # ### end Alembic commands ###
