"""empty message

Revision ID: b0ad2f01158b
Revises: 6d8bf60dc33c
Create Date: 2020-08-28 11:49:34.013235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ad2f01158b'
down_revision = '6d8bf60dc33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('n_thumb', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'n_thumb')
    # ### end Alembic commands ###
