"""empty message

Revision ID: c0d34225550c
Revises: b0ad2f01158b
Create Date: 2020-08-28 11:59:55.581795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0d34225550c'
down_revision = 'b0ad2f01158b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('n_thumb', sa.Integer(), nullable=False))
    op.drop_column('comment', 'n_thumb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('n_thumb', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('article', 'n_thumb')
    # ### end Alembic commands ###
