"""empty message

Revision ID: c72f543f1ca0
Revises: 521ba9aa5f0b
Create Date: 2020-08-26 16:29:41.495457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c72f543f1ca0'
down_revision = '521ba9aa5f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('uid', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('updated', sa.DateTime(), nullable=False))
    op.alter_column('article', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('article', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', mysql.VARCHAR(length=20), nullable=False))
    op.alter_column('article', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('article', 'updated')
    op.drop_column('article', 'uid')
    # ### end Alembic commands ###
