"""empty message

Revision ID: e300a261b9e4
Revises: eaed1e5989e8
Create Date: 2020-08-25 20:22:06.163260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e300a261b9e4'
down_revision = 'eaed1e5989e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
