"""empty message

Revision ID: eaed1e5989e8
Revises: 6b0c3a2e571a
Create Date: 2020-08-25 20:15:24.684876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaed1e5989e8'
down_revision = '6b0c3a2e571a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'now')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('now', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'create_time')
    # ### end Alembic commands ###
